### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by koko8463** [PiggyAwesome/Discord-Account-Generator#10]
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[2]/div/div[1]/div/div/div/form/div/div/div[5]/button/div"}
  (Session info: chrome=104.0.5112.102)
Stacktrace:
Backtrace:
        Ordinal0 [0x003D78B3+2193587]
        Ordinal0 [0x00370681+1771137]
        Ordinal0 [0x002841A8+803240]
        Ordinal0 [0x002B24A0+992416]
        Ordinal0 [0x002B273B+993083]
        Ordinal0 [0x002DF7C2+1177538]
        Ordinal0 [0x002CD7F4+1103860]
        Ordinal0 [0x002DDAE2+1170146]
        Ordinal0 [0x002CD5C6+1103302]
        Ordinal0 [0x002A77E0+948192]
        Ordinal0 [0x002A86E6+952038]
        GetHandleVerifier [0x00680CB2+2738370]
        GetHandleVerifier [0x006721B8+2678216]
        GetHandleVerifier [0x004617AA+512954]
        GetHandleVerifier [0x00460856+509030]
        Ordinal0 [0x0037743B+1799227]
        Ordinal0 [0x0037BB68+1817448]
        Ordinal0 [0x0037BC55+1817685]
        Ordinal0 [0x00385230+1856048]
        BaseThreadInitThunk [0x7758FA29+25]
        RtlGetAppContainerNamedObjectPath [0x778B7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x778B7A6E+238]

**Comment by TheBlackCookie** [comment]
What page does it fail at?

**Comment by koko8463** [comment]
at register the birth year it just types in the month section and then it crashes

**Comment by TheBlackCookie** [comment]
video?

**Comment by iGetUploaded** [comment]
> video?

https://gyazo.com/982e1c5b5690c1bd882ac39bb8ec8bda   heres a picture

**Comment by Gteditor99** [comment]
The issue seems to be here:

@PiggyAwesome you're using `typeSlow()` to type the dates; Which doesn't properly enter the birth information!
```py
year = str(random.randint(1970, 2000))
monthwords = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'Augustus', 'September', 'October', 'November', 'December']
day = str(random.randint(1,28))

...

typeSlow(random.choice(monthwords)) # Month
actions.send_keys(Keys.ENTER)
actions.perform()



sleep(0.4/speedMultiplier)

typeSlow(year) # Year
actions.send_keys(Keys.ENTER)
actions.perform()

sleep(0.5/speedMultiplier)
```
You should find the popup elements and use `click()`!

**Comment by PiggyAwesome** [comment]
Fixed

**Comment by iGetUploaded** [comment]
Still doing the whole birth thing in the 1st slot
