### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by burb7898** [PiggyAwesome/Discord-Account-Generator#14]
give me this when I run from CMD

Stacktrace:
Backtrace:
        Ordinal0 [0x008B6463+2188387]
        Ordinal0 [0x0084E461+1762401]
        Ordinal0 [0x00763D78+802168]
        Ordinal0 [0x00784E59+937561]
        Ordinal0 [0x00780A6C+920172]
        Ordinal0 [0x0077E331+910129]
        Ordinal0 [0x007B1430+1119280]
        Ordinal0 [0x007B108A+1118346]
        Ordinal0 [0x007AC5F6+1099254]
        Ordinal0 [0x00786BE0+945120]
        Ordinal0 [0x00787AD6+948950]
        GetHandleVerifier [0x00B571F2+2712546]
        GetHandleVerifier [0x00B4886D+2652765]
        GetHandleVerifier [0x0094002A+520730]
        GetHandleVerifier [0x0093EE06+516086]
        Ordinal0 [0x0085468B+1787531]
        Ordinal0 [0x00858E88+1805960]
        Ordinal0 [0x00858F75+1806197]
        Ordinal0 [0x00861DF1+1842673]
        BaseThreadInitThunk [0x76F6FEF9+25]
        RtlGetAppContainerNamedObjectPath [0x77C47BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77C47B8E+238]

**Comment by PiggyAwesome** [comment]
Did anything open?

**Comment by AkitoHorizon** [comment]
i've the sam but the chrome windows close after i run
