### ISSUE TITLE
help plz

### ISSUE THREAD

**Issue by AkitoHorizon** [PiggyAwesome/Discord-Account-Generator#17]
When i run the code with the command , the chrome windows write the account and close automatically , so i can't create the account and this happen :

Stacktrace:
Backtrace:
        GetHandleVerifier [0x0033DCE3+50899]
        (No symbol) [0x002CE111]
        (No symbol) [0x001D5588]
        (No symbol) [0x002008F9]
        (No symbol) [0x00200AFB]
        (No symbol) [0x0022F902]
        (No symbol) [0x0021B944]
        (No symbol) [0x0022E01C]
        (No symbol) [0x0021B6F6]
        (No symbol) [0x001F7708]
        (No symbol) [0x001F886D]
        GetHandleVerifier [0x005A3EAE+2566302]
        GetHandleVerifier [0x005D92B1+2784417]
        GetHandleVerifier [0x005D327C+2759788]
        GetHandleVerifier [0x003D5740+672048]
        (No symbol) [0x002D8872]
        (No symbol) [0x002D41C8]
        (No symbol) [0x002D42AB]
        (No symbol) [0x002C71B7]
        BaseThreadInitThunk [0x76BC00F9+25]
        RtlGetAppContainerNamedObjectPath [0x76FC7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x76FC7B8E+238]

**Comment by duckysucky121343** [comment]
its a simple fix. you need to update the xpath for the day input and continue button, as well as redo the date entry part. should take all of 2 minutes.
