### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dgd158** [PiggyAwesome/Discord-Account-Generator#3]
hi umm so the gen is ok it does open chrome and goes to the register page BUT when it goes to the register page it just stays doesnt do anything please fix it!

**Comment by nickacide** [comment]
8================================================================================D

**Comment by nickacide** [comment]
Imagine selling a shitty gen for $20

**Comment by Wafiismail27** [comment]
> hi umm so the gen is ok it does open chrome and goes to the register page BUT when it goes to the register page it just stays doesnt do anything please fix it!

Yeah it returns an error

**Comment by PiggyAwesome** [comment]
Should work now, thanks for the report!
