### ISSUE TITLE
Fix it!

### ISSUE THREAD

**Issue by VBPROGER** [PiggyAwesome/Discord-Account-Generator#5]
```
Traceback (most recent call last):
  File "/home/vbproger/Discord-Account-Generator/account_generator.py", line 32, in <module>
    username = ''.join(random.choice(string.digits + sting.ascii_letters) for i in range(8))
  File "/home/vbproger/Discord-Account-Generator/account_generator.py", line 32, in <genexpr>
    username = ''.join(random.choice(string.digits + sting.ascii_letters) for i in range(8))
NameError: name 'sting' is not defined
```
Why are you uploading code like this to Github?

**Comment by VBPROGER** [comment]
I know how to fix this, just reporting.

**Comment by Wafiismail27** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/vbproger/Discord-Account-Generator/account_generator.py", line 32, in <module>
>     username = ''.join(random.choice(string.digits + sting.ascii_letters) for i in range(8))
>   File "/home/vbproger/Discord-Account-Generator/account_generator.py", line 32, in <genexpr>
>     username = ''.join(random.choice(string.digits + sting.ascii_letters) for i in range(8))
> NameError: name 'sting' is not defined
> ```
> 
> Why are you uploading code like this to Github?

Can you tell me how to fix it

**Comment by VBPROGER** [comment]
Not "`sting`", "`string`".

**Comment by PiggyAwesome** [comment]
https://github.com/PiggyAwesome/Discord-Account-Generator/commit/672569059ef03cc68e6a7f22f2056b4cf03899cb
